using System.Collections.Generic;

namespace LibmpvIptvClient.Services.WebRemote
{
    public static class WebRemoteStrings
    {
        public static Dictionary<string, string> Get(string lang)
        {
            lang = (lang ?? "zh-CN").ToLowerInvariant();
            if (lang.StartsWith("en")) return En();
            if (lang.StartsWith("ru")) return Ru();
            if (lang.StartsWith("zh-tw") || lang.StartsWith("zh-hk")) return ZhTw();
            // 默认 zh-CN
            return ZhCn();
        }

        private static Dictionary<string, string> ZhCn() => new Dictionary<string, string>
        {
            ["title"] = "SrcBox 遥控器",
            ["theme_dark"] = "🌙 深色",
            ["theme_light"] = "☀️ 浅色",
            ["live_badge"] = "LIVE",
            ["status_stopped"] = "已停止",
            ["btn_fullscreen"] = "全屏",
            ["btn_play"] = "播放",
            ["btn_pause"] = "暂停",
            ["btn_stop"] = "停止",
            ["btn_mute"] = "静音",
            ["btn_prev"] = "上一台",
            ["btn_next"] = "下一台",
            ["btn_switch"] = "换源",
            ["btn_exit"] = "退出",
            ["btn_refresh"] = "刷新",
            ["section_channels"] = "频道列表",
            ["section_epg"] = "节目预告",
            ["epg_empty"] = "暂无节目信息",
            ["epg_select"] = "选择频道查看节目",
            ["loading"] = "加载中",
            ["connecting"] = "连接失败",
            ["mode_live"] = "直播",
            ["mode_replay"] = "回看",
            ["mode_timeshift"] = "时移",
            ["mode_recording"] = "录播",
            ["mode_local"] = "本地",
            ["mode_default"] = "已停止",
            ["epg_current"] = "正在播出",
            ["epg_replay_badge"] = "回看",
            ["epg_reminder_badge"] = "预约",
            ["epg_next"] = "下一节目",
            ["pwd_title"] = "请输入访问密码",
            ["pwd_placeholder"] = "密码",
            ["pwd_ok"] = "确认",
            ["pwd_error"] = "密码错误，请重试",
            ["exit_confirm"] = "确定要关闭播放器吗？",
            ["fav_star"] = "★",
            ["fav_group"] = "我的收藏",
        };

        private static Dictionary<string, string> En() => new Dictionary<string, string>
        {
            ["title"] = "SrcBox Remote",
            ["theme_dark"] = "🌙 Dark",
            ["theme_light"] = "☀️ Light",
            ["live_badge"] = "LIVE",
            ["status_stopped"] = "Stopped",
            ["btn_fullscreen"] = "Fullscreen",
            ["btn_play"] = "Play",
            ["btn_pause"] = "Pause",
            ["btn_stop"] = "Stop",
            ["btn_mute"] = "Mute",
            ["btn_prev"] = "Prev",
            ["btn_next"] = "Next",
            ["btn_switch"] = "Source",
            ["btn_exit"] = "Exit",
            ["btn_refresh"] = "Refresh",
            ["section_channels"] = "Channels",
            ["section_epg"] = "Program Guide",
            ["epg_empty"] = "No program info",
            ["epg_select"] = "Select a channel",
            ["loading"] = "Loading",
            ["connecting"] = "Connection failed",
            ["mode_live"] = "Live",
            ["mode_replay"] = "Replay",
            ["mode_timeshift"] = "Timeshift",
            ["mode_recording"] = "Recording",
            ["mode_local"] = "Local",
            ["mode_default"] = "Stopped",
            ["epg_current"] = "LIVE",
            ["epg_replay_badge"] = "Replay",
            ["epg_reminder_badge"] = "Reminder",
            ["epg_next"] = "Next",
            ["pwd_title"] = "Enter Password",
            ["pwd_placeholder"] = "Password",
            ["pwd_ok"] = "OK",
            ["pwd_error"] = "Wrong password, try again",
            ["exit_confirm"] = "Are you sure to close the player?",
            ["fav_star"] = "*",
            ["fav_group"] = "Favorites",
        };

        private static Dictionary<string, string> Ru() => new Dictionary<string, string>
        {
            ["title"] = "SrcBox Пульт",
            ["theme_dark"] = "🌙 Тёмная",
            ["theme_light"] = "☀️ Светлая",
            ["live_badge"] = "LIVE",
            ["status_stopped"] = "Остановлено",
            ["btn_fullscreen"] = "Полный экран",
            ["btn_play"] = "Воспр.",
            ["btn_pause"] = "Пауза",
            ["btn_stop"] = "Стоп",
            ["btn_mute"] = "Звук",
            ["btn_prev"] = "Пред.",
            ["btn_next"] = "След.",
            ["btn_switch"] = "Источник",
            ["btn_exit"] = "Выход",
            ["btn_refresh"] = "Обновить",
            ["section_channels"] = "Каналы",
            ["section_epg"] = "Программа",
            ["epg_empty"] = "Нет программы",
            ["epg_select"] = "Выберите канал",
            ["loading"] = "Загрузка",
            ["connecting"] = "Ошибка подключения",
            ["mode_live"] = "Прямой эфир",
            ["mode_replay"] = "Повтор",
            ["mode_timeshift"] = "Таймшифт",
            ["mode_recording"] = "Запись",
            ["mode_local"] = "Локально",
            ["mode_default"] = "Остановлено",
            ["epg_current"] = "В эфире",
            ["epg_replay_badge"] = "Повтор",
            ["epg_reminder_badge"] = "Напомнить",
            ["epg_next"] = "Следующая",
            ["pwd_title"] = "Введите пароль",
            ["pwd_placeholder"] = "Пароль",
            ["pwd_ok"] = "OK",
            ["pwd_error"] = "Неверный пароль",
            ["exit_confirm"] = "Закрыть плеер?",
            ["fav_star"] = "*",
            ["fav_group"] = "Избранное",
        };

        private static Dictionary<string, string> ZhTw() => new Dictionary<string, string>
        {
            ["title"] = "SrcBox 遙控器",
            ["theme_dark"] = "🌙 深色",
            ["theme_light"] = "☀️ 淺色",
            ["live_badge"] = "LIVE",
            ["status_stopped"] = "已停止",
            ["btn_fullscreen"] = "全螢幕",
            ["btn_play"] = "播放",
            ["btn_pause"] = "暫停",
            ["btn_stop"] = "停止",
            ["btn_mute"] = "靜音",
            ["btn_prev"] = "上一台",
            ["btn_next"] = "下一台",
            ["btn_switch"] = "換源",
            ["btn_exit"] = "退出",
            ["btn_refresh"] = "重新整理",
            ["section_channels"] = "頻道列表",
            ["section_epg"] = "節目預告",
            ["epg_empty"] = "暫無節目資訊",
            ["epg_select"] = "選擇頻道查看節目",
            ["loading"] = "載入中",
            ["connecting"] = "連線失敗",
            ["mode_live"] = "直播",
            ["mode_replay"] = "回看",
            ["mode_timeshift"] = "時移",
            ["mode_recording"] = "錄播",
            ["mode_local"] = "本地",
            ["mode_default"] = "已停止",
            ["epg_current"] = "正在播出",
            ["epg_replay_badge"] = "回看",
            ["epg_reminder_badge"] = "預約",
            ["epg_next"] = "下一節目",
            ["pwd_title"] = "請輸入存取密碼",
            ["pwd_placeholder"] = "密碼",
            ["pwd_ok"] = "確認",
            ["pwd_error"] = "密碼錯誤，請重試",
            ["exit_confirm"] = "確定要關閉播放器嗎？",
            ["fav_star"] = "★",
            ["fav_group"] = "我的收藏",
        };
    }
}
