using System.Collections.Generic;

namespace LibmpvIptvClient.Services.WebRemote
{
    public static class WebRemoteStrings
    {
        public static Dictionary<string, string> Get(string lang)
        {
            lang = (lang ?? "zh-CN").ToLowerInvariant();
            if (lang.StartsWith("en")) return En();
            if (lang.StartsWith("ru")) return Ru();
            if (lang.StartsWith("zh-tw") || lang.StartsWith("zh-hk")) return ZhTw();
            // 默认 zh-CN
            return ZhCn();
        }

        private static Dictionary<string, string> ZhCn() => new Dictionary<string, string>
        {
            ["title"] = "SrcBox 遥控器",
            ["theme_dark"] = "🌙 深色",
            ["theme_light"] = "☀️ 浅色",
            ["live_badge"] = "LIVE",
            ["status_stopped"] = "已停止",
            ["btn_fullscreen"] = "全屏",
            ["btn_play"] = "播放",
            ["btn_pause"] = "暂停",
            ["btn_stop"] = "停止",
            ["btn_mute"] = "静音",
            ["btn_prev"] = "上一台",
            ["btn_next"] = "下一台",
            ["btn_switch"] = "换源",
            ["btn_exit"] = "退出",
            ["btn_refresh"] = "刷新",
            ["section_channels"] = "频道列表",
            ["section_epg"] = "节目指南",
            ["epg_empty"] = "暂无节目信息",
            ["epg_select"] = "选择频道查看节目",
            ["loading"] = "加载中",
            ["connecting"] = "连接失败",
            ["mode_live"] = "直播",
            ["mode_replay"] = "回看",
            ["mode_timeshift"] = "时移",
            ["mode_recording"] = "录播",
            ["mode_local"] = "本地",
            ["mode_default"] = "已停止",
            ["epg_current"] = "正在播出",
            ["epg_replay_badge"] = "回看",
            ["epg_reminder_badge"] = "预约",
            ["epg_next"] = "下一节目",
            ["pwd_title"] = "请输入访问密码",
            ["pwd_placeholder"] = "密码",
            ["pwd_ok"] = "确认",
            ["pwd_error"] = "密码错误，请重试",
            ["exit_confirm"] = "确定要关闭播放器吗？",
            ["fav_star"] = "★",
            ["fav_group"] = "我的收藏",
        
            ["sec_sources"] = "源列表",
            ["btn_add_source"] = "+ 添加源",
            ["sec_reminders"] = "预约管理",
            ["sec_recordings"] = "录制管理",
            ["modal_add_source"] = "添加源",
            ["label_source_name"] = "源名称",
            ["label_source_url"] = "源地址",
            ["source_empty"] = "暂无源",
            ["source_active"] = "当前",
            ["source_select"] = "切换",
            ["source_remove"] = "删除",
            ["confirm_remove_source"] = "确定删除此源？",
            ["recording_empty"] = "暂无录制",
            ["recording_stop"] = "停止",
            ["recording_delete"] = "删除",
            ["reminder_empty"] = "暂无预约",
            ["reminder_cancel"] = "取消",
            ["modal_add_reminder"] = "添加预约",
            ["label_reminder_action"] = "预约类型",
            ["action_play"] = "预约播放",
            ["action_record_front"] = "前台录制",
            ["action_record_back"] = "后台录制",
            ["action_notify"] = "提醒",
            ["label_pre_alert"] = "提前提醒（秒）",
            ["btn_cancel"] = "取消",
            ["btn_confirm"] = "确认",
            ["btn_replay"] = "回放",
            ["btn_watch"] = "直播",
            ["btn_timeshift"] = "时移",
            ["btn_timeshift_on"] = "⏸ 时移",
            ["btn_timeshift_off"] = "⏵ 时移",
            ["btn_remind"] = "预约",
            ["btn_record"] = "录制",
            ["status_cancelled"] = "已取消",


            ["sec_sources"] = "Sources",
            ["btn_add_source"] = "+ Add Source",
            ["sec_reminders"] = "Reminders",
            ["sec_recordings"] = "Recordings",
            ["modal_add_source"] = "Add Source",
            ["label_source_name"] = "Source Name",
            ["label_source_url"] = "Source URL",
            ["source_empty"] = "No sources",
            ["source_active"] = "Active",
            ["source_select"] = "Select",
            ["source_remove"] = "Remove",
            ["confirm_remove_source"] = "Remove this source?",
            ["recording_empty"] = "No recordings",
            ["recording_stop"] = "Stop",
            ["recording_delete"] = "Delete",
            ["reminder_empty"] = "No reminders",
            ["reminder_cancel"] = "Cancel",
            ["modal_add_reminder"] = "Add Reminder",
            ["label_reminder_action"] = "Action",
            ["action_play"] = "Play",
            ["action_record_front"] = "Record (Front)",
            ["action_record_back"] = "Record (Back)",
            ["action_notify"] = "Notify",
            ["label_pre_alert"] = "Pre-alert (seconds)",
            ["btn_cancel"] = "Cancel",
            ["btn_confirm"] = "Confirm",
            ["btn_replay"] = "Replay",
            ["btn_watch"] = "LIVE",
            ["btn_timeshift"] = "Timeshift",
            ["btn_timeshift_on"] = "⏸ TS On",
            ["btn_timeshift_off"] = "⏵ TS Off",
            ["btn_remind"] = "Remind",
            ["btn_record"] = "Record",
            ["status_cancelled"] = "Cancelled",


            ["sec_sources"] = "Источники",
            ["btn_add_source"] = "+ Добавить",
            ["sec_reminders"] = "Напоминания",
            ["sec_recordings"] = "Записи",
            ["modal_add_source"] = "Добавить источник",
            ["label_source_name"] = "Название",
            ["label_source_url"] = "URL",
            ["source_empty"] = "Нет источников",
            ["source_active"] = "Активный",
            ["source_select"] = "Выбрать",
            ["source_remove"] = "Удалить",
            ["confirm_remove_source"] = "Удалить источник?",
            ["recording_empty"] = "Нет записей",
            ["recording_stop"] = "Стоп",
            ["recording_delete"] = "Удалить",
            ["reminder_empty"] = "Нет напоминаний",
            ["reminder_cancel"] = "Отмена",
            ["modal_add_reminder"] = "Добавить напоминание",
            ["label_reminder_action"] = "Действие",
            ["action_play"] = "Воспроизвести",
            ["action_record_front"] = "Запись (перед.)",
            ["action_record_back"] = "Запись (фон)",
            ["action_notify"] = "Уведомление",
            ["label_pre_alert"] = "Предв. оповещение (сек)",
            ["btn_cancel"] = "Отмена",
            ["btn_confirm"] = "ОК",
            ["btn_replay"] = "Повтор",
            ["btn_watch"] = "Эфир",
            ["btn_timeshift"] = "Таймшифт",
            ["btn_timeshift_on"] = "⏸ ТС вкл",
            ["btn_timeshift_off"] = "⏵ ТС выкл",
            ["btn_remind"] = "Напомнить",
            ["btn_record"] = "Запись",
            ["status_cancelled"] = "Отменено",


            ["sec_sources"] = "源列表",
            ["btn_add_source"] = "+ 新增源",
            ["sec_reminders"] = "預約管理",
            ["sec_recordings"] = "錄製管理",
            ["modal_add_source"] = "新增源",
            ["label_source_name"] = "源名稱",
            ["label_source_url"] = "源網址",
            ["source_empty"] = "暫無源",
            ["source_active"] = "當前",
            ["source_select"] = "切換",
            ["source_remove"] = "刪除",
            ["confirm_remove_source"] = "確定刪除此源？",
            ["recording_empty"] = "暫無錄製",
            ["recording_stop"] = "停止",
            ["recording_delete"] = "刪除",
            ["reminder_empty"] = "暫無預約",
            ["reminder_cancel"] = "取消",
            ["modal_add_reminder"] = "新增預約",
            ["label_reminder_action"] = "預約類型",
            ["action_play"] = "預約播放",
            ["action_record_front"] = "前置錄製",
            ["action_record_back"] = "背景錄製",
            ["action_notify"] = "提醒",
            ["label_pre_alert"] = "提前提醒（秒）",
            ["btn_cancel"] = "取消",
            ["btn_confirm"] = "確認",
            ["btn_replay"] = "回放",
            ["btn_watch"] = "直播",
            ["btn_timeshift"] = "時移",
            ["btn_timeshift_on"] = "⏸ 時移",
            ["btn_timeshift_off"] = "⏵ 時移",
            ["btn_remind"] = "預約",
            ["btn_record"] = "錄製",
            ["status_cancelled"] = "已取消",

};

        private static Dictionary<string, string> En() => new Dictionary<string, string>
        {
            ["title"] = "SrcBox Remote",
            ["theme_dark"] = "🌙 Dark",
            ["theme_light"] = "☀️ Light",
            ["live_badge"] = "LIVE",
            ["status_stopped"] = "Stopped",
            ["btn_fullscreen"] = "Fullscreen",
            ["btn_play"] = "Play",
            ["btn_pause"] = "Pause",
            ["btn_stop"] = "Stop",
            ["btn_mute"] = "Mute",
            ["btn_prev"] = "Prev",
            ["btn_next"] = "Next",
            ["btn_switch"] = "Source",
            ["btn_exit"] = "Exit",
            ["btn_refresh"] = "Refresh",
            ["section_channels"] = "Channels",
            ["section_epg"] = "Program Guide",
            ["epg_empty"] = "No program info",
            ["epg_select"] = "Select a channel",
            ["loading"] = "Loading",
            ["connecting"] = "Connection failed",
            ["mode_live"] = "Live",
            ["mode_replay"] = "Replay",
            ["mode_timeshift"] = "Timeshift",
            ["mode_recording"] = "Recording",
            ["mode_local"] = "Local",
            ["mode_default"] = "Stopped",
            ["epg_current"] = "LIVE",
            ["epg_replay_badge"] = "Replay",
            ["epg_reminder_badge"] = "Reminder",
            ["epg_next"] = "Next",
            ["pwd_title"] = "Enter Password",
            ["pwd_placeholder"] = "Password",
            ["pwd_ok"] = "OK",
            ["pwd_error"] = "Wrong password, try again",
            ["exit_confirm"] = "Are you sure to close the player?",
            ["fav_star"] = "*",
            ["fav_group"] = "Favorites",
        };

        private static Dictionary<string, string> Ru() => new Dictionary<string, string>
        {
            ["title"] = "SrcBox Пульт",
            ["theme_dark"] = "🌙 Тёмная",
            ["theme_light"] = "☀️ Светлая",
            ["live_badge"] = "LIVE",
            ["status_stopped"] = "Остановлено",
            ["btn_fullscreen"] = "Полный экран",
            ["btn_play"] = "Воспр.",
            ["btn_pause"] = "Пауза",
            ["btn_stop"] = "Стоп",
            ["btn_mute"] = "Звук",
            ["btn_prev"] = "Пред.",
            ["btn_next"] = "След.",
            ["btn_switch"] = "Источник",
            ["btn_exit"] = "Выход",
            ["btn_refresh"] = "Обновить",
            ["section_channels"] = "Каналы",
            ["section_epg"] = "Программа",
            ["epg_empty"] = "Нет программы",
            ["epg_select"] = "Выберите канал",
            ["loading"] = "Загрузка",
            ["connecting"] = "Ошибка подключения",
            ["mode_live"] = "Прямой эфир",
            ["mode_replay"] = "Повтор",
            ["mode_timeshift"] = "Таймшифт",
            ["mode_recording"] = "Запись",
            ["mode_local"] = "Локально",
            ["mode_default"] = "Остановлено",
            ["epg_current"] = "В эфире",
            ["epg_replay_badge"] = "Повтор",
            ["epg_reminder_badge"] = "Напомнить",
            ["epg_next"] = "Следующая",
            ["pwd_title"] = "Введите пароль",
            ["pwd_placeholder"] = "Пароль",
            ["pwd_ok"] = "OK",
            ["pwd_error"] = "Неверный пароль",
            ["exit_confirm"] = "Закрыть плеер?",
            ["fav_star"] = "*",
            ["fav_group"] = "Избранное",
        };

        private static Dictionary<string, string> ZhTw() => new Dictionary<string, string>
        {
            ["title"] = "SrcBox 遙控器",
            ["theme_dark"] = "🌙 深色",
            ["theme_light"] = "☀️ 淺色",
            ["live_badge"] = "LIVE",
            ["status_stopped"] = "已停止",
            ["btn_fullscreen"] = "全螢幕",
            ["btn_play"] = "播放",
            ["btn_pause"] = "暫停",
            ["btn_stop"] = "停止",
            ["btn_mute"] = "靜音",
            ["btn_prev"] = "上一台",
            ["btn_next"] = "下一台",
            ["btn_switch"] = "換源",
            ["btn_exit"] = "退出",
            ["btn_refresh"] = "重新整理",
            ["section_channels"] = "頻道列表",
            ["section_epg"] = "節目指南",
            ["epg_empty"] = "暫無節目資訊",
            ["epg_select"] = "選擇頻道查看節目",
            ["loading"] = "載入中",
            ["connecting"] = "連線失敗",
            ["mode_live"] = "直播",
            ["mode_replay"] = "回看",
            ["mode_timeshift"] = "時移",
            ["mode_recording"] = "錄播",
            ["mode_local"] = "本地",
            ["mode_default"] = "已停止",
            ["epg_current"] = "正在播出",
            ["epg_replay_badge"] = "回看",
            ["epg_reminder_badge"] = "預約",
            ["epg_next"] = "下一節目",
            ["pwd_title"] = "請輸入存取密碼",
            ["pwd_placeholder"] = "密碼",
            ["pwd_ok"] = "確認",
            ["pwd_error"] = "密碼錯誤，請重試",
            ["exit_confirm"] = "確定要關閉播放器嗎？",
            ["fav_star"] = "★",
            ["fav_group"] = "我的收藏",
        };
    }
}
