<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>SrcBox</AssemblyName>
    <ApplicationIcon>srcbox.ico</ApplicationIcon>
    <Product>SrcBox</Product>
    <AssemblyTitle>SrcBox</AssemblyTitle>
    <Version>1.1.9</Version>
    <AssemblyVersion>1.1.9.0</AssemblyVersion>
    <FileVersion>1.1.9.0</FileVersion>
    <GenerateProgramFile>false</GenerateProgramFile>
    <DisableWinExeConsoleOutput>true</DisableWinExeConsoleOutput>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Fleck" Version="1.2.0" />
    <PackageReference Include="ModernWpfUI" Version="0.9.6" />
    <PackageReference Include="System.Text.Encoding.CodePages" Version="8.0.0" />
    <PackageReference Include="Downloader" Version="4.1.1" />
  </ItemGroup>
  <ItemGroup>
    <Compile Remove="Tests\**\*.cs" />
    <None Include="Tests\**\*.cs" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="LICENSE.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="THIRD-PARTY-NOTICES.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="libmpv-2.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="libmpv-2.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <Resource Include="srcbox.png" />
    <Resource Include="srcbox.ico" />
  </ItemGroup>
</Project>
